### ISSUE TITLE
Develop unit test for all features

### ISSUE THREAD

**Issue by jacob-umich** [jacob-umich/ori-kinematics#10]
## Description
Create unit and verification tests for features and classes. Enable method of testing easily by adding a preprocessor macro.

## Tasks
- [ ] define unit and verification tests for edge generation
- [ ] define unit and verification tests for face generation
- [ ] define unit and verification tests for body generation
- [ ] define unit and verification tests for body connection
- [ ] define unit and verification tests for mesh data accessors
- [ ] define unit and verification tests for defining constraints from edges
- [ ] define unit and verification tests for defining constraints from global translation fixities
- [ ] define unit and verification tests for defining the constraint matrix 
- [ ] define unit and verification tests for redefining global translation fixities
- [ ] define unit and verification tests for computing admissible velocities
- [ ] define unit and verification tests for computing new node positions
- [ ] define unit and verification tests for any other relevant library functionality

## Definition of Done
Code is complete, all sections pass tests and cover most typical cases

**Comment by nzamb222** [comment]
Yeah that makes sense. Good to know in case we get asked the question. Will adjust slides accordingly
