### ISSUE TITLE
Implement python script to visualize simulation

### ISSUE THREAD

**Issue by jacob-umich** [jacob-umich/ori-kinematics#11]
## Description
The results of a kinematic simulation are easiest to determine visually. Because of this, we will use the Python scripting language in combination with the 3D modeling software, Blender. Blender has a built-in scripting API for Python, so implementing routines for animating 3D bodies should be straightforward. 

To begin the script, import blender's library. It will automatically be included with any script ran from blender.

`import bpy`

Then, an object and mesh can be defined. An object is analogous to a structure in our library, and a mesh is just the geometry data for an object. Each rigid body defined in our mesh should be included in the same blender object.

```
  mesh_data = bpy.data.meshes.new("_name")
  mesh_data.from_pydata(vertices,edges,faces)
  obj = bpy.data.objects.new('_objName',mesh_data)
  bpy.context.collection.objects.link(obj)
```

Where `vertices` define the coordinates of each node in a list `[x,y,z]`, `edges` are defined by a list of two nodes `[i,j]`, and `faces` are defined by a list of three or more nodes `[i,j,k]`. When a list of vertices is given to blender, each vertices is given a label according to its position in the `vertices` data structure.

Once `mesh_data` is defined, its properties can be changed to change the properties of the object in Blender. To update the position of nodes, the following property can be modified.

`mesh_data.vertices[i].co = [x,y,z]`

I believe individual coordinates can be too. For example, if you only want to update the x coordinate instead of all of them.

These few commands are enough to define the entire geometry of the problem, but when any changes are made to the geometry, Blender does not track the previous states. It only keeps track of the most current changes, and it must be told to keep track of all changes. This can be done by defining key frames. 

```
def insert_keyframe(fcurves, frame, values):
    for fcu, val in zip(fcurves, values):
        fcu.keyframe_points.insert(frame, val, options={'FAST'})

action = bpy.data.actions.new("MeshAnimation")
mesh_data.animation_data_create()
mesh_data.animation_data.action = action
data_path = "vertices[%d].co"
fcurve_list = []
for v in mesh_data.vertices:
    fcurves = [action.fcurves.new(f"vertices[{v.index}].co", index =  i) for i in range(3)]
    fcurve_list.append(fcurves)
for m in motions:
    update_geometry(m,mesh_data)
    for i,v in enumerate(mesh_data.vertices):
        insert_keyframe(fcurve_list[i],motion_index,v.co)
```

Blender mostly supports animation of global translation, rotation, or scaling, but is much less equiped to animate the deformation of meshes. To achieve this, we must make use of `fcurves`, which will encode the mesh data for each timestep. Each fcurve is tracking the motion of one vertex, so when the geometry is updated with `update_geometry` each fcurve needs to be updated.

This issue focuses on providing a script to generate animations based on the results of kinematic simulations performed by our library. In doing so, this issue satisfies the functional requirement "The library shall provide a method for visualizing the constrained motion"

## Tasks
- [ ] define a Python routine to instantiate the geometry based on our kinematic simulation
- [ ] define a Python routine to update the geometry of Blender's mesh
- [ ] define a Python routine to add a keyframe based on mesh updates.
- [ ] Create animations for each example case we define
## Definition of Done
This issue will be completed when a Python program is developed to provide visualization for any simulation performed by our library and animations are made for each example we defined.
