### ISSUE TITLE
Set up required libraries so they can be called in developed programs

### ISSUE THREAD

**Issue by jacob-umich** [jacob-umich/ori-kinematics#12]
## Description
Many performant software libraries have been developed to help programmers get the most out of their computer's hardware. Most CPU's have very complicated cache hierarchies and special instruction sets, and these libraries have been developed to fully take advantage of these. To re-create the algorithms they developed would take an enormous amount of time to just learn the target system's architecture. To save time, we will implement the algorithm's they have developed.

OpenBLAS, LAPack, PETSc, and MAGMA are all potential software libraries we may use. 
- OpenBLAS contains performant routines for basic linear algebra, such as matrix multiplication, and LAPack contains other, more sophisticated routines related to linear algebra.
- PETSc contains a wide variety of algorithms from ODE solvers to iterative solvers for linear systems of equations
- MAGMA was suggested by our instructor

While the installation of these libraries will be up to system our library will be ran on, we can develop our library such that it is easy to integrate these libraries if the user chooses. We can do this by using CMAKE to configure which libraries are used. Ideally, all libraries should be optional so the user can use our library without installing others at the cost of performance. This might be implemented the most easily by using conditional compiling and `#ifdef`.

This issue focuses on linking libraries such as openBLAS, Lapack for linear algebra routines, or any other performant libraries that will help in developing our libraries. This issue also fulfills the high-level requirement "The library shall make use of performant linear algebra libraries"

## Tasks
- [x] determine compilation commands
- [x] install libraries if needed
- [x] determine routine calls for matrix-vector multiplication
- [x] add CMake configure flags to determine which libraries are used
- [x] develop basic linear algebra functions that have a naïve implementation and an optimized implementation

## Definition of Done
Code functions and pasts tests. Reviewer comments are implemented
