### ISSUE TITLE
Create Presentation

### ISSUE THREAD

**Issue by jacob-umich** [jacob-umich/ori-kinematics#13]
## Description
This issue focuses on creating a presentation to showcase our work for this library. This presentation is required by the class and is graded on the following rubric

### Appearance
- 5 Speaker is appropriately dressed and speaks clearly and audibly.
- 2.5 Speaker is either not appropriately dress or does not speak clearly/understandably.
- 0 Speaker was not dressed appropriately and was hard to understand.
### Effectiveness
- 10 Outstanding organization of material. Visual aids readable and helped clarify/augmented presentation. No errors. Speaker engaged. Excellent use of space, gestures, and laser pointer.
- 8 Adequate organization of material. Visual aids are readable. No errors. Adequate use of space, gestures, and laser pointer.
- 6 Organization of material causes some confusion. Some visual aids are difficult to read. Minor errors. Use of space, gestures, or laser pointer distracts from presentation.
- 4 Organization of material is confusing. Visual aids are difficult to read. Contains errors causing confusion. Use of space,
gestures, or laser pointer distracts from presentation.
- 2 Organization of material prevented comprehension. Visual aids are not readable. Contains numerous errors or conflicting results. Dubious self-consistency.
- 0 Presentation not organized, has inconsistencies. Visual aids are not readable. Material is confusing.
### Q&A
- 5 Speaker was able to provide enlightening answers to challenging audience questions
- 2.5 Speaker was able to provide at least adequate answers to expected or reasonable audience questions.
- 0 Speaker could not answer any questions and/or could not comprehend any questions. 
### Time (20 min.)
- 5 Length of presentation was within 1 minute of target time with proper amount of time for questions.
- 2.5 Length of presentation was within 5 minutes of target time and inadequate time for questions.
- 0 Length of presentation was >10 minutes off of target time.

## Tasks
- [ ] define up to two slides per issue that can each be presented in a minute or less
- [ ] define an introduction slide
- [ ] define any other relevant slides
- [ ] rehearse presentation

## Description of Done
This issue will be complete when we have a rehearsed presentation that sufficiently covers the scope and details of our project in just 17 minutes.

**Comment by nzamb222** [comment]
Maybe add a quick slide on testing and verification? otherwise looks good
