### ISSUE TITLE
Create Report

### ISSUE THREAD

**Issue by jacob-umich** [jacob-umich/ori-kinematics#14]
## Description
This issue focuses on creating a report for our library, its features, the development process, and any other relevant details. This issue is required by our instructor. They provided us with a suggested outline for the report, which we will use. 

- Introduction (10 pts)
    - Include necessary background, motivation, and reiteration of project objectives
- Description of work performed (20 pts)
    - Tell me what you did
    - Highlight how it relates to course topics
- Results & Discussion (40 pts)
    - Explain observed results (not necessarily possible for all tasks e.g. documentation)
    - For work performed, that doesn't generate clear results provide arguments for why you did what you did (e.g. why you chose a particular design or why you chose a certain philosophy for testing, etc.)
    - Most important thing for this section is thoughtful/critical analysis of your work
- Conclusions (15 pts)
    - Did you meet your objectives? Why or Why not?
    - What did you learn?
    - What was the value of what you did?
    - What are some potential areas of future work?
- Bibliography/References (5 pts)
- English & grammar (10 pts)

The length of this report should be 10 to 15 pages. Sections will be graded independently as much as possible. Several reference reports were provided on [canvas](https://umich.instructure.com/courses/615189/assignments/2098455)

## Tasks
- [ ] generate introduction
- [ ] generate description of work
- [ ] generate result and discussion
- [ ] generate conclusion
- [ ] generate bibliography
- [ ] revise introduction
- [ ] revise description of work
- [ ] revise result and discussion
- [ ] revise conclusion
- [ ] revise bibliography
- [ ] polish report

## Definition of Done
This issue will be complete when we have a polished report that gives as much detail on our project within 10-15 pages.
