### ISSUE TITLE
Set up CMAKE and Project file structure

### ISSUE THREAD

**Issue by jacob-umich** [jacob-umich/ori-kinematics#3]
## Description

Libraries like this one need to be compiled in order for them to be used by others, and the nature of this compilation can be quite complicated. Because of this, several other software have been developed to help with this process. In our library, we will use CMake and make to help with the configuring, building (compiling), testing, and installing of our library. In general, CMake is a software that can configure and construct make files. If CMake is used correctly, no make files will need to be manaully created. This issue directly satisfies the high-level requirement "The library shall use a CMake based build system".

## Tasks
- [ ] Set up CMake files to include header files.
- [ ] Set up CMake files to build and run tests.
- [ ] Create a simple test to verify CMake is configured correctly.
- [ ] Set up CMake files to build and install the library.
- [ ] Set up CMake files to build the examples.
- [ ] Set up any CMake macros needed.
- [ ] Set up the project file structure such that CMake can be used easily.
- [ ] Modify existing source code so that the project builds and tests.

## Definition of Done

This issue will be complete when the library can be configured, built, tested, and installed using CMake and make, and it has a file structure to support these operations.
