### ISSUE TITLE
Set Up and manage GitHub

### ISSUE THREAD

**Issue by jacob-umich** [jacob-umich/ori-kinematics#4]
## Description
GitHub can be very useful for collaboration if used correctly. Issues can be assigned such that they represent tasks a person has to complete, work can be completed individually and merged later, and many supplementary features exist for both of these. This task focuses on using GitHub to make collaboration and task management for the project easier. Issues will allow for well-defined tasks, the code space will serve as storage for all our work, and GitHub's projects will help manage work

## Tasks
- [x] Create the repository.
- [x] define skeleton tasks that roughly resemble the steps required to complete the project. 
- [x] Assign tasks to users.
- [x] Create a project and any other metadata that will be useful in task management.
- [x] Ensure all tasks have enough details to be completed.
- [x] manage tasks as the project develops until completion.

## Definition of Done
This issue will be completed when the project is complete and the GitHub repository and project completely document our collaborative efforts.
