### ISSUE TITLE
Develop Program Architecture

### ISSUE THREAD

**Issue by jacob-umich** [jacob-umich/ori-kinematics#5]
## Description
In program development, many different development patterns can be used to achieve the same function. Having well-documented architecture for the developed software will not only avoid problems later in development, but they can help speed up development too. This issue will define two documents related to the program's architecture:

1. A class diagram showing every class in the library with their attributes and methods.
2. A state diagram showing 

These documents will be defined using the Unified Modeling Language and the plantUML tool.

## Tasks
- [x] Create a class diagram for the library
- [x] Create a state diagram for the library
- [ ] update diagrams as the library develops

## Definition of Done
This task will be completed when both diagrams are made and understood by the group
