### ISSUE TITLE
Define the project and issue-based-tasks

### ISSUE THREAD

**Issue by jacob-umich** [jacob-umich/ori-kinematics#6]
## Description
Creating well-defined issues will make developing the software for this project easier. This issue is focused on defining the problem, the project requirements (high-level and functional), and the steps needed to fulfill the project requirements.

## Tasks

- [x]  Define the problem
- [x]  Define the project requirements
- [x]  Define issue-based-tasks for developing the project's software

## Definition of Done

This task will be completed when a document is provided for the problem definition and project requirements and when task-based-issues are defined and understood by their assignee
