### ISSUE TITLE
Develop all features related to mesh generation

### ISSUE THREAD

**Issue by jacob-umich** [jacob-umich/ori-kinematics#7]
## Description
This task involves developing the software that creates a mesh for the given input structure. Since this is part of the library will be the user's first interaction with it, this task will also need to define the input format for defining the geometry of the problem. The mesh will be composed of nodes and edges, which will then be grouped by faces, bodies, and structures. 

Generally, if the rigid body is convex, the algorithm defined in the proposal can generate edges between all elements, which are crucial for defining constraints. 

Three or more edges define a face. Faces will mainly be used to organize edge elements but will also be useful when visualizing the prescribed kinematics. 

Four or more faces define a body. Bodies are used to group nodes, edges, and faces and are the largest class that is rigid. During simulation, the distance between all nodes of a body will remain the same. 

Structures are the main interface of this software. They group bodies and define how the bodies are connected. Bodies connected by one node form a ball and socket connection. Bodies connected by two nodes will form a hinge. Bodies connected by three or more nodes are rigidly connected and can be treated as one body. 

Given a list of nodes for a single body $p_0,...,p_n$ who have cartesian positions $\vec u_i = (x_i,y_i,z_i)$, we can generate the mesh the body's mesh by first selecting three arbitrary nodes that are not collinear. If these nodes are $p_0,p_1,p_2$, we can check if they are collinear by taking the dot product of two vectors $v_a$ and $v_b$ defined from the positions of the selected nodes.

$$ v_a = \frac{u_0-u_1}{||u_0-u_1||}$$

$$ v_b = \frac{u_0-u_2}{||u_0-u_2||}$$

$$ \alpha = v_a \cdot v_b $$

If $\alpha < 1$, then these nodes are not collinear. If this is true, these nodes can be connected and constrained to each other with the following constraint

$$ l_{ij}^2= ||u_i-u_j||^2$$

Where $l_{ij}$ is the original distance between the nodes. 

For every edge that is defined, a constraint equation is defined. These constraint equations will be useful in the later stages of the kinematic simulation.

Once the non-colinear points are connected, they can then be combined with another point such that they form a tetrahedron. If  $p_3$ is the new node that is selected and $v_a$ and $v_b$ are defined as before, a new vector $v_c$ can be defined.

$$ v_c = \frac{u_0-u_3}{||u_0-u_3||}$$

A matrix can be defined where vectors $v_a,v_b,and v_c$ are the columns of the matrix. If the determinant of this matrix is non-zero, then all four points form a tetrahedron. In this case, the new node can be connected to all existing nodes, making three new connections and constraint equations.

$$A = \left[\begin{array}{ccc} 
\vdots&\vdots&\vdots\\
v_a & v_b& v_c\\
\vdots&\vdots&\vdots\\\
\end{array}\right]$$

This process can be repeated for all nodes. This algorithm is sufficient to define the edges for a rigid body, but will not be able to define faces nicely. For example, if when a tetrahedron is formed, each coplanar set of nodes are made to define a face, some very interesting geometry results. From this, we will have to define another algorithm to define faces.

At some point, the defined rigid bodies will have to be connected to one another. This will be done by them sharing one or more nodes. All body-body connections must occur at nodes, and the user will define connections by which nodes are being connected. Once all bodies are connected, the nodes' degrees of freedom will be assigned coordinate numbers for use in defining the constraint matrix.

This issue also completes the project's functional requirement "The library shall generate a complete mesh of a system of rigid bodies given an input file of each rigid body's relevant vertices. "

## Tasks
- [ ] define the information that is needed in an input file.
- [ ] define the input file structure.
- [ ] define the best way for the user to give the input file to the library.
- [ ] Implement a method to define the mesh and coordinate information based on the input file.
- [ ] define an algorithm and method to determine faces.
- [ ] coordinate with other developers to see what else might be generated in the mesh and any other information that would be useful

## Definition of Done
This task will be complete when the library can be give a valid input file and it successfully defines edges, faces, bodies, and the connection between bodies so they can be used in later parts of the program. Additionally, any developed software must pass unit tests and validation tests for this issue to be complete
