### ISSUE TITLE
Develop all features related to defining the constraints

### ISSUE THREAD

**Issue by jacob-umich** [jacob-umich/ori-kinematics#8]
## Description
The constraint equations of a kinematic system determine what motions are admissible. Constraint equations can be defined from many circumstances, such as Newtonian physics, contact, friction, or geometry. The geometry constraints will be focused on by this library, where nodal locations of a rigid body must retain their originally specified distance from each other. These constraints can mainly be derived from the edges defined in each rigid body, but can also be defined from the connection of rigid bodies. If nodes $i$ and $j$ are connected by an edge, then their constraint equation would be

$$(u_i-u_j) \cdot (u_i-u_j) = l_{ij}^2$$

Where $l_{ij}$ is the original distance between nodes $i$ and $j$, $u_i$ is the 3D cartesian coordinates of node $i$

When two rigid bodies are connected, they are connected at nodes. In this way, their constraint equation are easily connected. This means two connected bodies will share one or more nodes as defined by the mesh's coordinate maps. Each constraint defined by the edges can then be linearized by taking its derivative with respect to time.

$$\frac{d}{dt}(u_i-u_j) \cdot (u_i-u_j) = \frac{d}{dt}l_{ij}^2$$

$$(u_i-u_j) \cdot (\dot u_i-\dot u_j) = 0 $$

$$ (x_i-x_j) (\dot x_i - \dot x_j)+(y_i-y_j) (\dot y_i - \dot y_j)+(z_i-z_j) (\dot z_i - \dot z_j) =0 $$

This constraint can be defined for each pair of nodes connected by an edge, and a system of equations results.

$$C \dot d = 0$$

Where $\dot d$ is a vector of velocities for each node's degrees of freedom

$$\dot d = \left[\begin{array}{c} 
\dot x_0\\
\dot y_0\\
\dot z_0\\
\vdots\\
\dot z_n\\
\end{array}\right]$$

Finally, some nodes will can be constrained relative to the global coordinate system. This can be done by simply requiring the specified degree of freedom's velocity to be zero, and this equation can be added to the constraint matrix.

$$ \dot x_i = 0 $$

The main objective of this task is to create a routine to define the constraint matrix based on the mesh defined elsewhere in the library and any degrees of freedom that are chosen to be constrained. This will be a sparse matrix that will be used by other routines to determine kinematically admissible motions. You might notice that this matrix depends on the collection of rigid bodies' current position, so for any integration scheme, this matrix will need to be recomputed for each time step.

## Tasks
- [x] develop a private method for the structure class to define the portion of the constraint matrix based on the edges defined in the mesh
- [x] develop a private method for the structure class to define the portion of the constraint matrix that locks the structure in relative to global translation
- [x] develop a public method to change the portion of the constraint matrix that locks the structure in relative to global translation
- [x] develop a public method that produces a complete constraint matrix based on the structure's current position.
- [x]  integrate one or more external routines from performant libraries such as openblas, lapack, petsc, or magma

## Definition of Done
This issue will be don when all methods used to define the constraint matrix are completely defined, the constraint matrix is usable by other routines in the library, and all unit tests and verification tests pass for methods defined in this task
