### ISSUE TITLE
Develop the remaining features needed to complete the kinematic simulation

### ISSUE THREAD

**Issue by jacob-umich** [jacob-umich/ori-kinematics#9]
## Description

The constraint matrix encodes all requirements for valid motion. Once the constraint matrix has been defined, kinematically admissible velocities can be computed by solving the following equation.

$$ C \dot d = 0 $$

However, $C \in \mathbb{R}^{n \times k}$  where $n < k $, so this system of equations has many solutions. An easier way to find kinematically admissible velocities is to project a target velocity profile onto the null space of the constraint matrix.

$$ \dot d = (I-C^{+}C)\dot d_0$$

Where $C^+$ is the psuedo-inverse of $C$ and $\dot d_0$ is the target velocity

In this way, the admissible velocity closest to the target velocity is chosen. Any numerical integration method may then be used to compute the displacements caused by these velocities. The simplest and most likely to cause errors for long simulations is the Euler method. Other methods that can be used are Heun's Method or any Runge-Kutta Method.

$$d_{i+1}=d_{i}+h\dot d_{i}$$

Where $h$ is the time step. Choosing a time step that is too large leads to larger distortion of the rigid bodies during simulation.

Finally, this is the user's last interaction with the library, so kinematic data will need to be returned to the user in some fashion. It might be stored in memory, in which case accessor methods should be defined or it might be written to a file or to the screen

This task focuses on providing routines to update nodal positions based on input target velocities, the previously defined mesh, and the constraint matrix defined for a structure's current position. In doing this, this issue is satisfying the functional requirement "The library shall compute a constrained set of velocities given a general velocity of interest and update the mesh positions based on a specified integration scheme."

## Tasks
- [ ] define a method of extracting angular and vector velocities from input file
- [ ] define a method on the structure class to update the structure's position for $n$ time steps of size $h$ given the target velocity $d_0$.
- [ ] integrate one or more external routines from performant libraries such as openblas, lapack, petsc, or magma
- [ ] Implement at least one other method for integrating velocities that has less truncation error than Euler's method
- [ ] define a method that allows the user to change the integration method
- [ ] define a method to return kinematic data to the user.

## Definition of Done

Methods are provided that can perform the kinematic simulation steps and the user is able to change the method integration. These methods pass all unit and validation tests.
